### ISSUE TITLE
Darstellung: Scrollbar in Loginfenster, etc.

### ISSUE THREAD

**Issue by subsven** [phmLabs/amilio.de#1]
Unter MacOS X mit Firefox 34.0.5 zeigt das Login-Fenster einen horizontalen Scrollbar.
Das auf einem Mac ohne Retina, kein Zoom im Browser. Kein Problem dagegen mit Safari und Chrome.

![amilio00](https://cloud.githubusercontent.com/assets/599016/5602864/b18e65e4-936a-11e4-850a-f2d89e4d6e9a.png)

**Comment by subsven** [comment]
Beim Produkt-URL-Eingeben-Fenster ragt das "Fenster schließen" in das Eingabefeld - waere da nicht eh ein [X] (graphisch) huebscher?
![amilio02](https://cloud.githubusercontent.com/assets/599016/5602918/28d674dc-936d-11e4-8fda-70d5aee73899.png)
Auch Achtung: "URL" (unten) vs. "Url" (links)

**Comment by subsven** [comment]
Textareas (Kanal-/Produkt-Eigenschaften) haben immer einen fixed-width-Font (hier: Courier), wogegen Texteingabefelder den normalen Font besitzen.

**Comment by subsven** [comment]
Auch noch eine Darstellungseigenart: Waehlt man ein Produkt, welches einen einen glatten Zehncent-Betrag kostet, so wird dies als "242.2" dargestellt, d.h. nicht mit zwei Nachkommastellen.

**Comment by subsven** [comment]
URLt man ein Produkt ohne Beschreibung, steht der entsprechende Hinweis voelligst im Off:
![amilio04](https://cloud.githubusercontent.com/assets/599016/5603136/2d406084-9375-11e4-88d7-c742db50e34d.png)

**Comment by subsven** [comment]
Zu lange Produkttitel bringen das Layout durcheinander
![amilio05](https://cloud.githubusercontent.com/assets/599016/5603153/ec07e172-9375-11e4-8458-a50f8c066697.png)

**Comment by subsven** [comment]
Hat ein Kanal einen zu langen Namen, so laesst sich der Slider zum Einpassen des Kanalbildes nicht mehr verschieben.
![amilio06](https://cloud.githubusercontent.com/assets/599016/5603165/c20237dc-9376-11e4-8926-c46dc8bf42d3.png)

**Comment by phmLabs** [comment]
Kanäle sind jetzt clickbar
Texte werden gekürzt (200 bei Produkt und 80 bei Kanal)

**Comment by phmLabs** [comment]
Url => Url
Produkt anlegen nicht mehr so dicht am Fenster schließen
Produkt erstellen => Produkt hinzufügen

**Comment by phmLabs** [comment]
Fixed font weg.

**Comment by phmLabs** [comment]
Würde ich mal schließen. 

Das mit dem Loginfenster-Scrolling musst du mir mal zeigen.

**Comment by subsven** [comment]
Das Loginfenster-Scrolling ist doch ganz oben im Screenshot zu sehen: am unteren Ende ist ein kleiner Scrollbar, den man ca. 5 Pixel nach rechts schieben kann, entsprechend verschiebt sich der Content des Loginfensters.
Auf meinem Mac isses jedenfalls so, mal morgen auf anderen Macs begutachten ;-)
