### ISSUE TITLE
Anmelde-Email landet im Spam

### ISSUE THREAD

**Issue by chluehr** [phmLabs/amilio.de#10]
Die EMails werden anscheinend direkt vom Webserver gesendet (Ohne entsprechende DKIM/SPF Eintraege) und landen daher wahrscheinlich (wie bei mir) im Spam. Per MailJet/Mandrill kann man das relativ einfach loesen.

**Comment by chluehr** [comment]
Absender ist auch noch: webmaster webmaster@example.com

**Comment by phmLabs** [comment]
![screenshot 2015-01-05 15 14 09](https://cloud.githubusercontent.com/assets/650537/5614092/92249b86-94ed-11e4-9928-f1fca4d48de7.jpeg)

Bei mir kommt das von ner anderen Adresse an und landet auch nicht im Spam.

**Comment by chluehr** [comment]
sorry, ja, der absender oben ist nur bei der passwort vergessen funktion (ich nahm an, das waere identisch)

**Comment by phmLabs** [comment]
Neu: https://github.com/phmLabs/amilio.de/issues/11

**Comment by phmLabs** [comment]
@chluehr kannst du noch mal testen? Habe das E-Mailing auf dem Server neu aufgesetzt und die MX-Einträge geradegebogen.

**Comment by chluehr** [comment]
Ja, sieht prinzipiell besser aus (SPF passt) (nen bischen privacy-editiert):

```
Received: from euveXXXX.serverXXXX.de (euveXXXX.serverXXXXX.de. [62.75.XXX.XXX])
        by mx.google.com with ESMTP id jo9si35240778wjc.128.2015.01.12.04.XXX.XXX
        for <chris@XXXXXXX.de>;
        Mon, 12 Jan 2015 04:42:51 -0800 (PST)
Received-SPF: pass (google.com: domain of register@amilio.de designates 62.75.XXX.XXX as permitted sender) client-ip=62.75.XXX.XXX;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of register@amilio.de designates 62.75.XXX.XXX as permitted sender) smtp.mail=register@amilio.de
Received: from www.amilio.de (localhost.localdomain [127.0.0.1])
    by euveXXXX.serverXXXX.de (Postfix) with ESMTP id 200964D613DE
    for <chris@XXXXX.de>; Mon, 12 Jan 2015 12:42:21 +0000 (UTC)
```

Allerdings meint Google weiterhin, es sei Spam "Why is this message in Spam? It's similar to messages that were detected by our spam filters." - Das kann sich aber mit der Zeit geben ..

Meine Empfehlung ist tatsaechlich, das Senden von Mails nicht selber zu machen :-)

**Comment by phmLabs** [comment]
@chluehr Kannst du noch mal testen? Habe auf mandrill umgestellt.

**Comment by phmLabs** [comment]
Done. Mandrill.
