### ISSUE TITLE
Passwort vergessen: Absender nicht amilio.de sondern example.com

### ISSUE THREAD

**Issue by phmLabs** [phmLabs/amilio.de#11]

**Comment by chluehr** [comment]
gmail: http://awesomescreenshot.com/08f44spm19
header enthaelt:

Received-SPF: fail (google.com: domain of webmaster@example.com does not designate 62.XXX.XXX.XXX as permitted sender) client-ip=XXX.XXX.XXX.87;
Authentication-Results: mx.google.com;
       spf=fail (google.com: domain of webmaster@example.com does not designate XXX.XXX.XXX.87 as permitted sender) smtp.mail=webmaster@example.com

**Comment by phmLabs** [comment]
Könnte mir vorstellen, dass das weggeht, wenn man die Adresse anpasst.

2015-01-05 15:18 GMT+01:00 Christoph Lühr notifications@github.com:

**Comment by chluehr** [comment]
ich habe identische header auch bei der registrierung erhalten (und auch da im spam)

```
Received-SPF: none (google.com: register@amilio.de does not designate permitted sender hosts) 
```

**Comment by phmLabs** [comment]
# app/config/config.yml

fos_user:
    db_driver:              ~ # Required
    firewall_name:          ~ # Required
    user_class:             ~ # Required
    use_listener:           true
    use_username_form_type: true
    model_manager_name:     null  # change it to the name of your entity/document manager if you don't want to use the default one.
    from_email:
        address:        webmaster@example.com
        sender_name:    webmaster

**Comment by phmLabs** [comment]
Absender ist jetzt reset@amilio.de
