### ISSUE TITLE
Kann Produkt nicht hinzufügen

### ISSUE THREAD

**Issue by subsven** [phmLabs/amilio.de#16]
Folgendes Produkt lässt sich nicht hinzufügen, nach dem Ausfüllen der fehlenden Produktbeschreibung mit irgendwas kommt immer reproduzierbar ein 500er-Fehler:

http://www.amazon.de/Unisex-Erwachsene-Pokemon-Pikachu-Printed/dp/B00R66XBXO/ref=sr_1_45?ie=UTF8&qid=1420495275&sr=8-45&keywords=emoji

Kanal ist dabei egal. Fehlerzeitpunkt ca. 2015-01-05 23:03 MET.

**Comment by phmLabs** [comment]
Amazon gibt kein Bild zurück bei dem Produkt, was bedeutet, dass wir es nicht anzeigen können.

Würde das einfach schließen und ggf. die Fehlermeldung anpassen wenn sich noch mal jemand beschwert.
