### ISSUE TITLE
Produkt kann doppelt in eigenen Kanal "kopiert" werden

### ISSUE THREAD

**Issue by subsven** [phmLabs/amilio.de#18]
Kopiert man ein Produkt in einen eigenen Kanal und ruft danach erneut diesen Dialog im fremden Kanal auf, kann man das gleiche Produkt wiederum in den gleichen eigenen Kanal kopieren, so dass es danach zweimal vorhanden ist. Eigentlich könnte der eigene Kanal gleich im Dropdown ausgeschlossen werden, wenn diese Instanz des Produkts bereits dort referenziert ist (dass es eine Referenz und keine Kopie ist, erkennt man ja daran, dass man das Produkt nicht bearbeiten kann).

Was passiert eigentlich, wenn der Eigner des Produkts dieses löscht? Entfällt es dann auch allen Kanälen?

Btw. hier noch ein voelligstes Nischenproblem :-)
![amilio08](https://cloud.githubusercontent.com/assets/599016/5621195/82808ef6-9533-11e4-8d71-0773220f8d35.png)

**Comment by phmLabs** [comment]
Da weiss ich nicht so genau, ob es nicht ein Feature ist. Wenn ich über Jahre einen Kanal pflege, möchte ich doch vielleicht, dass ein Produkt wieder oben erscheint, ohne dass man die "Kompostion" von vor Jahren zerreist.

**Comment by phmLabs** [comment]
Lassen wir so.
