### ISSUE TITLE
Broken Image in Produkterfassungsfenster

### ISSUE THREAD

**Issue by subsven** [phmLabs/amilio.de#2]
Wurden die Produktinformationen nicht automatisch ausgelesen, dann werden Eingabefenster fuer die Textfelder dargestellt, aber fuer das Bild nur zwei Broken Images - was soll man den da nur machen?!
![amilio01](https://cloud.githubusercontent.com/assets/599016/5602899/8ade6b18-936c-11e4-94a2-3f8402ee5ee7.png)

PS Firefox 34.0.5/Mac OS X

**Comment by phmLabs** [comment]
Sollte behoben sein.
