### ISSUE TITLE
Produktseite

### ISSUE THREAD

**Issue by bogomolov-dev** [phmLabs/amilio.de#20]
Wenn man die Produktseite mit langen Texten aufruft, so sieht man nicht den ganzen Inhalt. Man kann da auch nicht hinscrollen. Das könnte helfen:

```
#modalDialogContent { overflow-y: auto; }
```

Ebenso werden HTML-Tags weder interpretiert noch entfernt.

Beispiel: http://www.amilio.de/product/282/entwurfsmuster-elemente-wiederverwendbarer-objektorientierter-software.html#87

**Comment by phmLabs** [comment]
Done. Aber noch nicht schön.

Mache im internen Tracker noch ein beautification-Ticket auf.
