### ISSUE TITLE
Registrierungsmail ohne Footer

### ISSUE THREAD

**Issue by ghost** [phmLabs/amilio.de#21]
> Hallo sasmeyer,
> wir freuen uns sehr, dass du dich für amilio interessierst. Bitte besuche folgenden Link, um dein Benutzerkonto zu bestätigen:
> http://www.amilio.de/register/confirm/xxxx
> 
> Viel Spaß mit deinen Kanälen,
> das amilio-Team

In Deutschland besser einen "Impressum"-Absender hinzufügen

**Comment by phmLabs** [comment]
Ist drinnen.
