### ISSUE TITLE
Usability: Text in Profil 

### ISSUE THREAD

**Issue by ghost** [phmLabs/amilio.de#22]
![amilio_uberuns](https://cloud.githubusercontent.com/assets/10420531/5630380/a65b583a-95bd-11e4-8ac3-307b70e28a44.PNG)

**Comment by ghost** [comment]
1. Der Lauf der Schrift ist sehr breit und dadurch anstrengend zu lesen
2. Schrift ist recht klein bei 100%

**Comment by phmLabs** [comment]
@sasmeyer schau mal: http://www.amilio.de/app_dev.php/Sascha/seemannsgarn/

besser?

**Comment by ghost** [comment]
Passt. Nun kann man es gut lesen.

2015-01-22 7:18 GMT+01:00 Nils Langner notifications@github.com:

**Comment by phmLabs** [comment]
Done.
