### ISSUE TITLE
SEO: URL-Generierung

### ISSUE THREAD

**Issue by ghost** [phmLabs/amilio.de#25]
Vorschlag: URL Generierung abhängig von Kanal / Kollekationen Sturktur aufsetzen.
Struktur: www.amilio.de/user/kanal/kollektion/Produkt

aktuell: 
http://www.amilio.de/u/zuhause
http://www.amilio.de/c/97/badezimmer.html

**Comment by phmLabs** [comment]
Ist sicherlich sinnvoll, wobei das Produkt nicht an der Kollektion hängt, sondern frei. Es zeigen ja viele Kanäle auf das gleiche Produkt und da will man nur einen Endpunkt haben. Aber User/Kanal/Kollektion finde ich erstmal gut, auch wenn die Namen dann recht lang werden können.

**Comment by phmLabs** [comment]
Ist umgebaut. Produkt hängt aber an einer anderen URL. 

/zuhause/firmen/195-normann-kopenhagen.html
/zuhause/firmen/
/zuhause/

Umleitung haben wir jetzt erstmal nicht, da wir noch nicht wirklich im Google index sind.
