### ISSUE TITLE
500er beim Anlegen eines Produkts :(

### ISSUE THREAD

**Issue by christianhaller** [phmLabs/amilio.de#26]
https://www.dropbox.com/s/0lp4x25vb6td5ka/Screenshot%202015-02-15%2011.16.49.png?dl=0

**Comment by phmLabs** [comment]
Kannst du mir die Produkt-URL einmal schicken?

2015-02-15 11:21 GMT+01:00 Christian Haller notifications@github.com:

**Comment by christianhaller** [comment]
Das ist dieses super Produkt
http://www.amazon.de/gp/product/B001KYVJSC

**Comment by phmLabs** [comment]
RegExes angepasst:

``` php
        $patterns[] = '^/dp/(.*)/^';
        $patterns[] = '^/product/(.*)/^';
        $patterns[] = '^product/(.*)^';
```

Sollte jetzt gehen.

**Comment by christianhaller** [comment]
Ich komme jetzt ein modales Fenster weiter und bleibe dann da hängen.

**Comment by phmLabs** [comment]
Bei mir geht's :(

http://www.amilio.de/product/1349/subtle-butt-einweg-gasneutralisator.html#216

**Comment by phmLabs** [comment]
Geht bei mir. Schließe das Ticket.
