### ISSUE TITLE
Eigenartiges Verhalten bei ungueltigem Preis

### ISSUE THREAD

**Issue by subsven** [phmLabs/amilio.de#4]
Gibt man bei der Produkterfassung einen ungültigen Preis ein (z.B. "abcd"), so kommt ein ungestylter Fehlerdialog. Korrigiert man in diesem den Preis und sendet den Dialog erneut ab, so kommt eine 500-"An Error Occurred"-Seite.
![amilio03](https://cloud.githubusercontent.com/assets/599016/5603041/2aa15e4e-9372-11e4-9fa9-d4d611c12bdd.png)

**Comment by phmLabs** [comment]
Ist behoben.
