### ISSUE TITLE
500er-Fehler beim Folgen eines eigenen Kanals

### ISSUE THREAD

**Issue by subsven** [phmLabs/amilio.de#5]
Folgt man einem eigenen Kanal mittels "Herzchen" und klickt danach erneut auf das Herzchen, um dem Kanal nicht mehr zu folgen, kommt eine 500-"An Error Occurred"-Seite.

**Comment by phmLabs** [comment]
Sollte gefixed sein. Jetzt wird überprüft, ob bereits gefollowed wird.
