### ISSUE TITLE
Twitter-Sharing-Beschreibung von Produktseiten falsch

### ISSUE THREAD

**Issue by subsven** [phmLabs/amilio.de#7]
Klickt man innerhalb eines Kanals (oder auf der "Dein Netzwerk"-Seite) auf ein Produkt, so erscheint dessen Seite in einem Overlay. Twittert man von dort dieses Produkt, so hat der Tweet die Beschreibung der Basis-Seite (d.h. des Kanals oder "Dein Netzwerk") als Inhalt und nicht den Namen des Produkts.
Die enthaltene URL zeigt jedoch korrekterweise auf die Produktseite.
Da wird wohl noch ein wenig JavaScript-title-Aenderungs-Magie notwendig sein.

![amilio08](https://cloud.githubusercontent.com/assets/599016/5603451/fdb87a16-9385-11e4-83e2-2076bc5c1eb0.png)

**Comment by subsven** [comment]
Wohl aehnlich begruendet ist, dass bei Facebook-Liken im Overlay immer bei Facebook nur "amilio - Das soziale Produktnetzwerk" ankommt (ohne jegliche Produkteigenschaften), obgleich der Link brav auf die Produktseite zeigt (die wiederum standalone keine Facebook- und Twitter-Buttons besitzt?!)

![amilio07](https://cloud.githubusercontent.com/assets/599016/5603447/c9be695a-9385-11e4-8dc5-f8e3c2ced459.png)

**Comment by phmLabs** [comment]
Sollte gehen, nachdem ich die Aktualisierung händisch mache.

**Comment by subsven** [comment]
Ja, sieht beides nun gut aus :+1:
