### ISSUE TITLE
Email-Link: "Bitte besuche folgenden Link, um dein Benutzerkonto zu bestätigen" - Error

### ISSUE THREAD

**Issue by chluehr** [phmLabs/amilio.de#8]
http://www.amilio.de/register/confirm/K5Rfyl9... fruehrt zu: 
"ops! An Error Occurred The server returned a "404 Not Found".

**Comment by phmLabs** [comment]
Komisch, hab grad einen Account angelegt und lief durch. Welchen Usernamen hattest du?

**Comment by chluehr** [comment]
luehr@r-pentomino.de

**Comment by phmLabs** [comment]
Hmm, bei mir geht's. Habe auch einen Usernamen genommen, der ein Leerzeichen drinnen hat.

**Comment by chluehr** [comment]
OK, gerade passwort vergessen verwendet, das ging - allerdings lande ich dann zum schluss (klick auf link in email) auf einer seite ohne layout: http://awesomescreenshot.com/01144sode5 
einloggen geht aber immer noch nicht. 
Ich versuche jetzt mal ein "simpleres" Passpwort (meins ist 16 zeichen inkl. vieler sonderzeichen)

**Comment by chluehr** [comment]
Vielleicht ist mein account immer noch im status "nicht bestaetigt" - aber ich kann trotzdem die passwort vergessen funktion verwenden? (falls dem so ist, sollte da vielleicht ein hinweis kommen)

**Comment by phmLabs** [comment]
Kannst du mal den ganzen Link posten? Der sieht sehr abgeschnitten aus.

**Comment by chluehr** [comment]
das war extra ... aber hier der ganze:
http://www.amilio.de/register/confirm/K5Rfyl9-wsxL19QEdPCU57vhtCBUIMtj0_1JL9plp08

**Comment by phmLabs** [comment]
Ich glaube das FOSUserBundle schickt ein 404 wenn man den Lin schon benutzt hat. Muss ich mal rausfinden.

Gruß
Nils

 
Nils Langner
Head of Quality Management
 

G+J DIGITAL PRODUCTS

Am Baumwall 11
20459 Hamburg

Telefon +49 (0) 40 / 37 03 - 7556
E-Mail langner.nils@guj.de
www.guj.de
G+J Digital Products GmbH | Sitz: Hamburg, Amtsgericht Hamburg 
HRB 36884 | Geschäftsführer: Oliver von Wersch, Eva-Maria Bauch |
Ein Unternehmen von Gruner + Jahr
Bitte denken Sie an die Umwelt, bevor Sie drucken.

Am 5. Januar 2015 bei 15:45:44, Christoph Lühr (notifications@github.com) schrieb:

das war extra ... aber hier der ganze:
http://www.amilio.de/register/confirm/K5Rfyl9-wsxL19QEdPCU57vhtCBUIMtj0_1JL9plp08

**Comment by phmLabs** [comment]
Würde ich als gelöst ansehen. Mittlerweile geht auch die Anmeldung per E-Mail-Adresse.
