### ISSUE TITLE
Anmeldung (Login) fuehrt zu Full-Site Fehlermeldung im Login-iFrame

### ISSUE THREAD

**Issue by chluehr** [phmLabs/amilio.de#9]
"Zugriff verboten

Ups. Es sieht so aus, als ob du gerade versucht hast eine Seite zu besuchen, für die du keine Rechte besitzt. Dies kann passieren, wenn du zum Bispiel nicht angemeldet bist. Versuche es doch nach der Anmeldung einfach noch einmal und schau was passiert.
- See more at: http://www.amilio.de/system/notallowed/#sthash.3gGwqFY5.dpuf "

**Comment by phmLabs** [comment]
Sieht so aus, dass das passiert, wenn man die Credentials falsch eingibt.

**Comment by chluehr** [comment]
schau mal, habs gerade auf simpel geaendert: luehr@r-pentomino.de / pass: 12345678

**Comment by phmLabs** [comment]
Nimm mal deinen Usernamen und nicht deine E-Mail.-Adresse. Dann geht's bei mir.

**Comment by chluehr** [comment]
hm - hatte ich da einen angegeben bei der registrierung? mein LastPass (PW manager) hatte da meine email gespeichert - meine ueblichen verdaechtigen (nutzernamen) gehen auch nicht; Nerve ich eigentlich? koennen auch gerne chatten ...

**Comment by phmLabs** [comment]
Ich glaube so ist besser, dann haben wir eine Historie wenn es wieder auftritt. Dein Username ist "Christoph Lühr".

**Comment by chluehr** [comment]
ok - klappt!

**Comment by phmLabs** [comment]
Trotzdem leitet es auf die falsche Seite weiter, wenn man die Credentials falsch hat :)

**Comment by phmLabs** [comment]
E-Mail auch als Nutzername möglich:
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/logging_by_username_or_email.md

**Comment by phmLabs** [comment]
Ging über Config:

```
            failure_path: fos_user_security_login
```
